rybakdigital/ucc

- Tests/Data/Types/Basic/BasicTypeTest.php
- Tests/Data/Types/Basic/IntegerTypeTest.php
- Ucc/Data/Types/Basic/BasicTypes.php
- Ucc/Data/Types/Basic/IntegerType.php
- Ucc/Data/Types/TypeInterface.php
- Ucc/Exception/InvalidDataTypeException.php
* Adds `BasicTypes` with checks for integer
* Adds `IntegerType`
> Data types basic type

- Tests/Data/Types/Basic/BasicTypeTest.php
- Tests/Data/Types/Basic/StringTypeTest.php
- Ucc/Data/Types/Basic/BasicTypes.php
- Ucc/Data/Types/Basic/StringType.php
* Adds `StringType` class
* Adds `StringType` to `BasicTypes`
> Data types string type

- Tests/Data/Types/Basic/BasicTypeTest.php
- Tests/Data/Types/Basic/IntegerTypeTest.php
- Tests/Data/Types/Basic/StringTypeTest.php
- Ucc/Data/Types/Basic/IntegerType.php
- Ucc/Data/Types/Basic/StringType.php
- Ucc/Exception/Data/InvalidDataException.php
- Ucc/Exception/Data/InvalidDataTypeException.php
- Ucc/Exception/Data/InvalidDataValueException.php
* renames and moves Exceptions
> Renames Exceptions

- Ucc/Data/Types/Basic/IntegerType.php
> Adds examples

- Tests/Data/Types/Pseudo/FilterTypeTest.php
- Tests/Data/Types/Pseudo/PseudoTypesTest.php
- Ucc/Data/Types/Basic/BasicTypes.php
- Ucc/Data/Types/Pseudo/FilterType.php
- Ucc/Data/Types/Pseudo/PseudoTypes.php
- Ucc/Filter/Criterion/Criterion.php
* Adds `PseudoTypes`
* Adds `FilterType`
> Ucc data types pseudo

- Tests/Data/Format/Display/DisplayTest.php
- Ucc/Data/Format/Display/Display.php
- Ucc/Data/Format/Display/DisplayInterface.php
- Ucc/Data/Sortable/Sort/SortInterface.php
* Adds `Display` and `DispalyInterface` to manage formatting
> Data format display

- Tests/Data/Types/Pseudo/DisplayTypeTest.php
- Tests/Data/Types/Pseudo/PseudoTypesTest.php
- Ucc/Data/Types/Pseudo/DisplayType.php
- Ucc/Data/Types/Pseudo/PseudoTypes.php
* Adds `DisplayType` to pseudo types
> Display type

- Tests/Data/Format/Format/FormatTest.php
- Ucc/Data/Format/Display/Display.php
- Ucc/Data/Format/Display/DisplayInterface.php
- Ucc/Data/Format/Format/Format.php
- Ucc/Data/Format/Format/FormatInterface.php
> Adds Format

- Tests/Data/Types/Pseudo/FormatTypeTest.php
- Tests/Data/Types/Pseudo/PseudoTypesTest.php
- Ucc/Data/Format/Format/Format.php
- Ucc/Data/Types/Pseudo/FormatType.php
- Ucc/Data/Types/Pseudo/PseudoTypes.php
Adds `FormatType` to `PseudoTypes`
> Format type

- Ucc/Data/Filter/Criterion/Criterion.php
- Ucc/Data/Filter/Criterion/CriterionInterface.php
- Ucc/Data/Format/Display/Display.php
- Ucc/Data/Format/Display/DisplayInterface.php
- Ucc/Data/Sortable/Sort/Sort.php
- Ucc/Data/Sortable/Sort/SortInterface.php
> Updates doc blocks

- Tests/Data/Filter/Clause/ClauseTest.php
> Fixes php compatibility

- Tests/Data/Filter/Criterion/CriterionTest.php
- Tests/Data/Types/Pseudo/FilterTypeTest.php
> Adds few tests to increase coverage

- Tests/Db/Filter/SqlTest.php
- Ucc/Db/Filter/Sql.php
> Returns SQLClause

- Tests/Db/Filter/SqlTest.php
- Ucc/Db/Filter/Sql.php
* Adds tests for direct SQL translation
> Adds tests for direct sql translation

- Tests/Db/Filter/SqlTest.php
- Ucc/Db/Filter/Sql.php
* Adds relative comparison test
> Test db sql

- Tests/Db/Filter/SqlTest.php
- Ucc/Db/Filter/Sql.php
* Adds tetsts for db-filter-sql
> Tests db filter sql

- Tests/Db/Filter/SqlTest.php
- Ucc/Db/Filter/Sql.php
> Adds regex test

- Tests/Db/Filter/SqlTest.php
- Ucc/Db/Filter/Sql.php
> Test db filter sql

- Tests/Data/Filter/Clause/ClauseTest.php
- Tests/Db/Filter/FiterTest.php
- Tests/Db/Filter/SqlTest.php
- Ucc/Data/Filter/Clause/Clause.php
- Ucc/Db/Filter/Filter.php
- Ucc/Db/Filter/Sql.php
* Fixes `Filter` to `Clause` transformation
* Adds tests
* patches for method names
> Ucc db filters fix

- Tests/Db/Filter/FiterTest.php
- Ucc/Db/Filter/Filter.php
> Adds method to process multiple filters at the time

- Tests/Db/Filter/FiterTest.php
- Ucc/Db/Filter/Filter.php
> Updates tests

- Tests/Data/Validator/Check/CheckTest.php
- Tests/Data/Validator/ValidatorTest.php
- Ucc/Data/Types/Basic/BasicTypes.php
- Ucc/Data/Types/Pseudo/PseudoTypes.php
- Ucc/Data/Validator/Check/Check.php
- Ucc/Data/Validator/Validator.php
> Ucc data validator

- Ucc/Data/Validator/Validator.php
- Ucc/Data/Validator/ValidatorInterface.php
> Adds validator Inteface

- Tests/File/FileTest.php
- Tests/File/Path/PathTest.php
- Ucc/File/File.php
- Ucc/File/Path/Path.php
* Adds `Ucc File` to library- collection of simple methods related to common operations on files
> Adds File to ucc

- Tests/File/Path/PathTest.php
- Ucc/File/Path/Path.php
> Fixes typo in method name

- Tests/File/Path/PathTest.php
- Ucc/File/Path/Path.php
* Fixes bug in file path extension matxhing
> Fixes extension matxhing method

- Tests/File/FileTest.php
- Tests/_resources/content.json
- Tests/_resources/content.txt
- Ucc/File/File.php
* Fixes `File::getContent()` and adds tests
* Fixes alias method `File::load()`
> Fixes File::getContent() and adds tests

- Ucc/File/Path/Path.php
> Checks if index 1 is set

- Tests/Data/Types/Pseudo/FilterTypeTest.php
- Tests/Data/Types/Pseudo/PseudoTypesTest.php
- Tests/Db/Filter/FiterTest.php
- Tests/Db/Sql/Query/QueryTest.php
- Ucc/Data/Types/Pseudo/FilterType.php
- Ucc/Data/Types/Pseudo/PseudoTypes.php
- Ucc/Db/Filter/Sql.php
- Ucc/Db/Sql/Query/Query.php
* Major fixes to Data Filter: returning Filter object rather than array of data for checks, changes method name to more significant one;
* Major fixes to Db Query and Sql: fixes filter methods, returns Query object rather than SQL Statement, etc
* Updates tests
> Data and db fixes

- Tests/Db/Connection/ConnectionTest.php
- Ucc/Db/Connection/Connection.php
- Ucc/Exception/Db/DbConnectionException.php
> Db connection

- .travis.yml
- Tests/Db/Result/ResultTest.php
- Ucc/Db/Connection/Connection.php
- Ucc/Db/Result/Result.php
* Add `Ucc\Db\Result\Result` - class to hold mysql result set
* Modifies Connection to allow different ports
> Adds result

- Tests/Crypt/HashTest.php
- Tests/phpunit.xml
- Ucc/Crypt/Hash.php
* Adds `Hash` class that provides methods to encrypt objects
> Adds Crypt functions

- README.md
- Ucc/Crypt/Hash.php
- docs/Hash.md
* Adds documentation for `Hash` class
> Adds docs for Crypt

- Tests/Data/Types/Basic/BasicTypeTest.php
- Tests/Data/Types/Basic/EmailTypeTest.php
- Ucc/Crypt/Hash.php
- Ucc/Data/Types/Basic/BasicTypes.php
- Ucc/Data/Types/Basic/EmailType.php
* Adds EmailType
* Adds EmailType to BaseTypes
> Email type

- Tests/Data/Types/Basic/BasicTypeTest.php
- Tests/Data/Types/Basic/BooleanTypeTest.php
- Ucc/Data/Types/Basic/BasicTypes.php
- Ucc/Data/Types/Basic/BooleanType.php
* Adds `BooleanType` check
* Adds `checkBoolean()` to `BasicTypes`
> Adds BooleanType check

- Tests/Data/Types/Basic/PhoneNumberTypeTest.php
- Ucc/Data/Types/Basic/PhoneNumberType.php
* Sri Lanka
* Turkey
* Kyrgyzstan
* India
> [Phone] - Adds sri Lanka phone number

- Tests/Data/Filter/FilterTest.php
- Ucc/Data/Filter/Filter.php
- composer.json
- composer.lock
Adds new array helper methods:
* `removeCriterion`
* `findCriterion`
> Updates Filter class

- Tests/Data/Types/Basic/PhoneNumberTypeTest.php
- Ucc/Data/Types/Basic/PhoneNumberType.php
Adds support for HongKong numbers
> Adds support for HongKong numbers

- Tests/Data/Types/Basic/PhoneNumberTypeTest.php
- Ucc/Data/Types/Basic/PhoneNumberType.php
> Adds Laotian phone numbers

- Tests/Data/Types/Basic/PhoneNumberTypeTest.php
- Ucc/Data/Types/Basic/PhoneNumberType.php
> Adds support for Afghan phone numbers

- Tests/Data/Types/Basic/PhoneNumberTypeTest.php
- Ucc/Data/Types/Basic/PhoneNumberType.php
> Adds Burmese numbers

- Tests/Data/Types/Basic/PhoneNumberTypeTest.php
- Ucc/Data/Types/Basic/PhoneNumberType.php
> Adds Support for Maldivian numbers

- Tests/Data/Types/Basic/PhoneNumberTypeTest.php
- Ucc/Data/Types/Basic/PhoneNumberType.php
Adds support for Zone 5 phone numbers
> Adds support for Zone 5 phone numbers

- Ucc/Db/Filter/Dql.php
> Fixes DQL Boolean bug
